// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'
import { IMAGES_API_URL } from '@/constants/constants'

interface IGalleryApiResponse {
  [key: string]: number | string | any
}

export const galleryApiSlice = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: IMAGES_API_URL,
  }),
  reducerPath: 'galleryApi',
  tagTypes: ['Images'],
  endpoints: (build) => ({
    getImages: build.query<IGalleryApiResponse, number>({
      query: (page = 1) =>
        `?image_type=all&orientation=all&per_page=12&key=22984321-98218ca8e9b1f3be57a008ac4&q&q=hdr&page=${page}`,
      providesTags: (result, error, id) => [{ type: 'Images', id }],
    }),
  }),
})

// Hooks are auto-generated by RTK-Query
export const { useGetImagesQuery } = galleryApiSlice
